### ISSUE TITLE
barbordersize=0 does not work in version 2.2.1

### ISSUE THREAD

**Issue by xiekunwhy** [royfrancis/pophelper#10]
Hi, me again, I was update pophelper to v2.2.1, but it was a nightmare for me, all style are change because barborders were added and barbordersize = 0 does not work. Can you please check and enable barbordersize = 0 and reproduce the style in v2.2.0(without barborder).
[v2.2.1_barbordersize_0.pdf](https://github.com/royfrancis/pophelper/files/1251347/v2.2.1_barbordersize_0.pdf)
[v2.2.0.pdf](https://github.com/royfrancis/pophelper/files/1251346/v2.2.0.pdf)

**Comment by royfrancis** [comment]
Sorry about that. Try `barbordersize=NA`. I will change that to the default.

**Comment by xiekunwhy** [comment]
Barbordersize=NA worked for me, thank you very much!

**Comment by royfrancis** [comment]
`barbordersize` issue fixed in v2.2.2.
