### ISSUE TITLE
Graphs in graphics device instead of direct file export

### ISSUE THREAD

**Issue by SamWittwer** [royfrancis/pophelper#13]
Hi! I love the package, it makes my work with STRUCTURE a lot easier already. I like the plotting functions included in the package but I would love to plot them on a graphics device instead of having them directly as a file export so I can integrate the graphs into my R notebook (for example the `evannoMethodStructure()` function). Is there a straightforward way of doing this?

**Comment by royfrancis** [comment]
Hi, I am afraid directly returning a plot object has not been implemented. I am hoping to do this at some point. As of now, the plot is always exported. One way to work around this is to export the plot, and then display that file in your interactive document. See an example chunk in Rmarkdown below:

```r
```{r}
library(pophelper)

sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
slist <- readQ(files=sfiles)

em <- evannoMethodStructure(summariseQ(tabulateQ(slist)),writetable=F)
knitr::include_graphics("evannoMethodStructure.png")
```
```

**Comment by royfrancis** [comment]
`evannoMethodStructure()`, `plotQ()` and `plotQMultiline()` returns plot objects for use in RMarkdown. Added in version `2.2.4`.
