### ISSUE TITLE
Separate individual labels from group labels

### ISSUE THREAD

**Issue by markusruhsam** [royfrancis/pophelper#15]
Hi Roy,

First of all you've done an amazing job with customising the plots! However, there's one thing I'd like to do which I haven't been able to sort. Is it possible to 'de-concatenate' the individual labels from the group labels? I am using plotQMultiline with group and individual labels but would like to display the individual labels ONLY below the bars and not the individual and group lables concatenated. As the group labels are displayed above the bars I don't see the necessety to have them concatenated to the individual labels as well as this makes the graph/ind labels unecessarily long and crowded.

Thanks for your help

Markus

**Comment by royfrancis** [comment]
Hi Markus, Sounds like a good idea. I can try to make some changes.

**Comment by royfrancis** [comment]
New argument `indlabwithgrplab=F` added to `plotQ()` and `plotQMultiline()` to control whether group labels are concatenated to individual labels. Added in version `2.2.4`.
