### ISSUE TITLE
Evanno plots

### ISSUE THREAD

**Issue by markusruhsam** [royfrancis/pophelper#19]
Hi,

Is it possible to produce the Evanno plots in a way that the value for K on the x-axis always corresponds to integers.  I usually get plots where K is labelled in fractions on the x - axis starting at K=2.5 - 5 - 7.5 ....... (see attached plot)?

Thank you

Markus

[evannoMethodStructure.pdf](https://github.com/royfrancis/pophelper/files/1647024/evannoMethodStructure.pdf)

**Comment by royfrancis** [comment]
Added two arguments `xaxisbreaks` and `xaxislabels` to control x-axis labelling. You can specify custom breaks like so:

```
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
sf <- summariseQ(tabulateQ(readQ(sfiles)))
ev <- evannoMethodStructure(sf,returnplot=T,exportplot=F,returndata=F,xaxisbreaks=c(2,4,6))
```

**Comment by markusruhsam** [comment]
Excellent! Thanks for your quick fix!
