### ISSUE TITLE
ability to sort discontinuous groups

### ISSUE THREAD

**Issue by ewarschefsky** [royfrancis/pophelper#2]
Could you make it possible to sort by group even if the group information is not continuous? 

In my dataset, individuals are not in order of population in the original structure file, but are mixed up (Pop1, Pop3, Pop4, Pop1, Pop2, Pop2, Pop1...), and are likewise mixed in the meanQ file. When I ask it to add group labels it just gives each individual a label (except in the case where multiple individuals from the same group are adjacent, in which case it will group them). If I try to sort by group or subset, it says that it cannot do so with discontinuous groups.

**Comment by royfrancis** [comment]
The order of the individuals remains the same as in the input file. The group labels provided is in the same order as well. When using sorting without group labels, all individuals are sorted. When sorting with group labels, individuals are sorted within the groups. Group labels do not move around and non-contiguous groups with same labels do not get merged. If your individuals/groups are not in the correct order in the meanQ file, I guess you will have to do a bit of manual sorting.

+ Read in the meanQ file to R.
+ Read in your group/pop labels to R.
+ Join both of them into the same dataframe.
+ Sort them the way you like.
+ Then use the numeric part as as a qlist to input to plotQ and labels part as input to grplab.

Reproducible example below using a structure file: 

```R
library(pophelper)

# DEMO OF THE ISSUE
sfiles <- list.files(path=system.file("files/structure",package="pophelper"),full.names=T)
# read the data file
data1 <- readQ(files=sfiles[1])
# read the label file with duplicate blocks of labels
labs1 <- read.delim(system.file("files/structuregrplabels-rep.txt", package="pophelper"), header=F,stringsAsFactors=F)$V1
# plot: sorts within groups
plotQ(qlist=data1,grplab=list("lab1\n"=labs1), sortind="Cluster1")
```
![structure_01](https://cloud.githubusercontent.com/assets/5083500/21884952/d25375d4-d8b5-11e6-8dac-78e5b431dd04.png)
```R
# plot: cannot subset or reorder because pop A is duplicate and non-contiguous
plotQ(qlist=data1,grplab=list("lab1\n"=labs1), subsetgrp = "Pop A")
```
```diff
- Error in pophelper:::grpLabels(df = df1, grplab = grplab[[pp]], subsetgrp = subsetgrp,  : grpLabels: Duplicated contiguous block of grp labels. Not possible to subset or reorder grps.
```
The solution is below.
```R
# WORK AROUND
# get the dataframe from the list
data2 <- data1[[1]]
# add the group labels to the data frame
data2$grp <- labs1
# sort the dataframe by group and save to new dataframe
data3 <- data2[order(data2$grp),]
head(data3)

# create a new qlist with sorted data
data4 <- list("run1"=data3[,1:2])

# plot
plotQ(qlist=data4,grplab=list("lab1\n"=data3$grp))
```
![run1](https://cloud.githubusercontent.com/assets/5083500/21885208/e523971a-d8b6-11e6-9455-e389c899ab08.png)
```R
# plot with sort
plotQ(qlist=data4,grplab=list("lab1\n"=data3$grp), sortind="Cluster1")
```
![run1](https://cloud.githubusercontent.com/assets/5083500/21885233/fdf2e5d4-d8b6-11e6-99f5-dfd905132170.png)
```R
# plot with subset
plotQ(qlist=data4,grplab=list("lab1\n"=data3$grp), sortind="Cluster1", subsetgrp = c("Pop B","Pop A"))
```
![run1](https://cloud.githubusercontent.com/assets/5083500/21885279/34114c96-d8b7-11e6-8bcf-59ff082d968b.png)

You can close this issue if this works for you or get back to me.

**Comment by ewarschefsky** [comment]
Thanks for the quick response and solution! I still think it would be nice to have the option to do this within pophelper, but this will work.
