### ISSUE TITLE
how to italicize group labels

### ISSUE THREAD

**Issue by ashaff4** [royfrancis/pophelper#20]
I cannot figure out how to italicize my group labels in my plotQMultiline. The labels are imported from a .csv. Any suggestions? Thank you!

qfile <- "clumpp_k=3_interr.txt"
readQ(qfile)
qlist <- readQ(files=qfile)
subsplab3 <- metadata1
plotQMultiline(qlist,showindlab=F,subsetgrp=c("S. p. interrupta","S. p. putorius","S. p. ambarvalis"),font="italic",useindlab=F,ordergrp=T,showlegend=F,showtitle=F,showsubtitle=F,titlelab="The Great Structure",grplabsize=6,subtitlelab="The amazing population structure of your favourite organism.",grplabbgcol="gray", height=2,indlabsize=2.5,clustercol=c("darkslategray4","chocolate1", "black"),indlabspacer=-1,   barbordercol="white",barbordersize=0,spl=46,outputfilename="Plot_Interr_K=3,imgtype="jpeg")

**Comment by royfrancis** [comment]
Hmm.. I don't think there is an easy straightforward way to do it as of now. I could add an option for it in a future release.

**Comment by ashaff4** [comment]
No problem, thanks for the reply! It would be nice to see it in the future
release, if possible!

On Feb 6, 2018 6:39 AM, "Roy Francis" <notifications@github.com> wrote:

Hmm.. I don't think there is an easy straightforward way to do it as of
now. I could add an option for it in a future release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/royfrancis/pophelper/issues/20#issuecomment-363409946>,
or mute the thread

**Comment by royfrancis** [comment]
Italic labels for group labels implemented in version 2.2.6. Set `grplabface="italic"`.
