### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by GiselT** [royfrancis/pophelper#23]
Hello, can someone help me?
I have a version of R 3.4.1 and I can not install the POPHELPER package ...
Could someone pass me the script?
thank you very much

Gisel

**Comment by royfrancis** [comment]
I am guessing you are trying to install from CRAN, perhaps from within RStudio. The package is not on CRAN. It won't work. Try this.

```
# install dependencies and devtools
install.packages(c("Cairo","ggplot2","gridExtra","gtable","tidyr","devtools"),dependencies=T)

# install pophelper package from GitHub
devtools::install_github('royfrancis/pophelper')
```

**Comment by GiselT** [comment]
Thank you so much for your help!! 

Gisel

**Comment by royfrancis** [comment]
Welcome :-)
