### ISSUE TITLE
problems in running pophelper

### ISSUE THREAD

**Issue by ytguojian** [royfrancis/pophelper#25]
Hi, 
where is the protocol for plot admixture results? I  was not familiar with R. So what is the protocol file that I could use? I have get the ***.Q and ***.P files from k2 to k15.
Thanks a lot.

cheers,
Jian

**Comment by royfrancis** [comment]
First, you need to install R and the pophelper package and dependencies as shown on the [home page](https://github.com/royfrancis/pophelper). Then run the following.

```r
library(pophelper)

# choose your run files (I think the Q files)
files <- choose.files(multi=TRUE)

# read data into R
qlist <- readQ(files)
```

Once the data is read in, you can tabulate the runs or plot them.

```r
# tabulate runs
df1 <- tabulateQ(qlist)

# summarise runs
df2 <- summariseQ(df1)

# plot singleline runs
plotQ(qlist)
plotQ(qlist,imgoutput="join")

# plot multiline runs
plotQMultiline(qlist[1])

# clumpp export (to align cluster between runs within single K)
clumppExport(qlist)
```

Lot more details are [here](http://royfrancis.github.io/pophelper/).
