### ISSUE TITLE
.meanQ file for K=4 plotting only 3 colors

### ISSUE THREAD

**Issue by gigiudicelli** [royfrancis/pophelper#26]
Hi,

I'm using Pophelper to visualize my results from fastStructure. When I plot my .meanQ file for K=4 I can't distinguish four clusters; for some reason, I just visualize three colors in the plot itself, the legend and all the rest looks fine, as you can see in the figure below. This problem also occurs for others K>4. I realize that in all my .meanQ files for K=4 and K>4 I have a column where the values of the cluster are all the same. I'm not sure if this is something relevant or if it is correlated. 

My script:

plotQ(qlist_k4[1],imgoutput="sep", showsp = F, height = 5.0,
      clustercol = c("blue", "darkorange", "black", "green"), barsize = 1.0, 
      showtitle=T, titlelab="P. axillaris subsp. parodii", titlesize = 7.0, titlespacer = 0.5,
      showsubtitle = T, subtitlelab = "Pampas division", subtitlesize = 4.0, subtitlespacer = 0.5,
      showlegend = T, legendtextsize = 4.0, legendlab = c("RS", "URU", "Chaco", "Name"),
      useindlab = T, showindlab = T, indlabheight = 1.5, indlabsize = 1.0, 
      indlabcol = "black", indlabangle = 90, indlabvjust = 0.5, indlabspacer = -1,
      ordergrp = T, barbordercolour = "white", barbordersize = 0,
      outputfilename = "plotq_k4", dpi = 600, imgtype = "png")

My plot:
![plotq_k4](https://user-images.githubusercontent.com/37419016/37488092-4f0872ca-2872-11e8-8aa8-95ef3e03b036.png)
A exemple of (part of) my .meanQ file (K=4), where all individuals of the first column present the same value:

0.000008  0.999976  0.000008  0.000008
0.000008  0.999976  0.000008  0.000008
0.000008  0.999976  0.000008  0.000008
0.000008  0.000008  0.000008  0.999976
0.000008  0.999976  0.000008  0.000008
0.000008  0.999976  0.000008  0.000008
0.000008  0.188496  0.143361  0.668136
0.000008  0.041626  0.071271  0.887095
0.000008  0.000008  0.000008  0.999976
0.000008  0.013699  0.243100  0.743193
0.000008  0.000008  0.000008  0.999976
0.000008  0.180609  0.089187  0.730196
0.000008  0.000008  0.000008  0.999976
0.000008  0.000008  0.000008  0.999976
0.000008  0.000008  0.000008  0.999976

I would like to know if I'm plotting something wrong or if perhaps there's a problem with my .meanQ file. I just use readQ followed by plotQ functions for this analysis, I don't have to use clumppExport for .meanQ files, right?

Best regards,

Giovanna Giudicelli

**Comment by royfrancis** [comment]
Hi Giovanna,
Sorry for the delayed reply. I somehow missed your message. From above, I think it works alright. You don't see the colours in plot, because the proportion values are too low.
