### ISSUE TITLE
Divider lines are currently not printed on 'join' plots with group labels and sorting other than 'label'.

### ISSUE THREAD

**Issue by DanielEPlatt** [royfrancis/pophelper#27]
I would like to add divider lines to a join plot sorted with 'all.'  How do I do this?

**Comment by royfrancis** [comment]
Yea. I've been hoping to work on that part, but I just didn't have the time. I will get back to you on this.

**Comment by royfrancis** [comment]
In a joined plot with group labels, if you sort by all, then each run will end up with a different order of individuals. And then it no longer fits with the group labels below.

**Comment by royfrancis** [comment]
Ignore my previous comment :)

**Comment by royfrancis** [comment]
Divider lines are now printed with joined plots, group labels and sorting in version 2.2.6.

**Comment by DanielEPlatt** [comment]
THANK YOU!!!

Best,
Dan

**Comment by royfrancis** [comment]
You are welcome! Try it out and if you come across any issues, or something looks odd, let me know.
