### ISSUE TITLE
How groups are assigned to samples ?

### ISSUE THREAD

**Issue by fredlecerf** [royfrancis/pophelper#28]
Hi,

I'm working with the output of admixture. So, I have a file with this format:
0.000011 0.000019 0.000010 0.999930 0.000010 0.000010 0.000010
0.000010 0.000010 0.000010 0.999940 0.000010 0.000010 0.000010

I've got 150 lines like that. I want to plot this result with group information. In the doc of pophelper, you indicate to generate a dataframe (in my case, only one column) with the same number of lines. So, I generate this kind of dataframe with the name of my groups in the same line order of the sample in the result file (As I'm tested your package, you would see that this data frame has the same name as in the example).

`onelabset <- pop[,1,drop=FALSE]`

and 

`plotQ(d,returnplot=T,exportplot=F,grplab=onelabset)`

with `d <- readQ(files="result.7.Q",filetype="basic")`

The R console returns me this:
`$plot`
`$plot[[1]]`
`TableGrob (4 x 1) "arrange": 2 grobs`
`  z     cells    name           grob`
`1 1 (1-3,1-1) arrange gtable[layout]`
`2 2 (4-4,1-1) arrange gtable[layout]`

`$data`
`$data$qlist`
`[1] NA`
``
`$data$grplab`
`[1] NA``

I don't know what to do to solve this problem...

**Comment by royfrancis** [comment]
It looks like it's working. Since you included `returnplot=T`, a plot object is returned. And since you specified `exportplot=F`, no plot is exported. You can remove both of these options, and you should have an image exported to your working directory.

**Comment by fredlecerf** [comment]
Curious thing is : when I tested the plotQ without the `grplab` option but with the `returnplot=T,exportplot=F`, a plot was generated in the output of Rstudio...

**Comment by lmarieslava** [comment]
Hi! I had the same issue where the graph wasn't being previewed in R, and I did the same thing, however the plot being exported to my working directory is not sorting by "all" which causes my grouplabels to be all over the place, there's also a really bad quality going on, I tried changing the sizes of everything so it's bigger including the indvlabsize but it just makes my bars longer but not thicker. 

This is the code I am using 

p4 <- plotQ(slist[1],
            height = 1,
            imgoutput = "sep",
            clustercol = c("#CCFF99","#FFFF66","#CC99FF","#99CCFF"),
            sortind = "all", #Sort plot by one specific Cluster or by all
            useindlab=T, #Use individuals labels
            showindlab = T, #Individuals names below plot
            indlabheight = 0.3,
            indlabsize = 2,
            grplab = onelabset,
            linesize=0.5,
            barsize = 1,
            barbordersize = 0.1,
            barbordercolour = "white",
            pointsize=4,
            showdiv = T,
            splabsize = 15,
            legendtextsize = 30,
            splab = c("K4"),
            spbgcol = "white",
            basesize=5,
            exportpath=getwd())
            
            And this is how the graph was coming out before adding the grplab options (in the Rstudio graph plot view) 
            
            
![image](https://github.com/royfrancis/pophelper/assets/169286591/3b7c987c-4cf8-4b8e-8cae-dcb781b4c109)

vs how it's coming out rn being exported

![image](https://github.com/royfrancis/pophelper/assets/169286591/cb05a007-dec1-4557-a740-37a1c6bc6916)

I don't know what could be causing this, please help
