### ISSUE TITLE
Change sample names in plotQMultiline

### ISSUE THREAD

**Issue by markusruhsam** [royfrancis/pophelper#3]
Hello,

I was wondering if it's possible to have the actual sample names in the multi-line plot instead of the numbers?

Thank you

Markus

![image](https://cloud.githubusercontent.com/assets/23214870/22208348/788cdf90-e17a-11e6-804c-60d9d72e653d.png)

**Comment by royfrancis** [comment]
By default, it labels numerically 1, 2, 3 ... If you set the option `useindlab=T`, then labels are taken from input list object. The rownames of the list object are used as individual names. Here is a working example below:

```r
library(pophelper)

#read structure file
sfiles <- list.files(path=system.file("files/structure",package="pophelper"),full.names=T)
slist <- readQ(files=sfiles[1])

# plot using numeric numbering
plotQMultiline(slist,useindlab=F)

#plot using labels from the input (no change because input rownames are 1, 2, 3 ...)
plotQMultiline(slist,useindlab=T)

#read new labels
inds <- read.delim(system.file("files/structureindlabels.txt",package="pophelper"),header=FALSE,stringsAsFactors=FALSE)

# add labels as rownames to qlist
rownames(slist[[1]]) <- inds$V1

# plot with new labels.
plotQMultiline(slist,useindlab=T)

# plot without using labels from input.
plotQMultiline(slist,useindlab=F)
```

**Comment by markusruhsam** [comment]
That’s great. Thank you!

Markus

**Comment by markusruhsam** [comment]
Hi Roy,

I just ran through the script with the following commands but the plot still had only the rownames in the plot.

> setwd(choose.dir())
> library(pophelper)
Loading required package: Cairo
Loading required package: ggplot2
pophelper v2.0.0 ready.
> sfiles <- choose.files()
> slist <- readQ(files=sfiles)
> inds <- read.delim("mylabels.txt",header=FALSE,stringsAsFactors=FALSE)
> rownames(slist[[1]]) <- inds$V1
> plotQMultiline(slist[c(6)], lpp=7, spl=70, useindlab=T, imgtype="pdf")
20000_run_6_f-Multiline-1.pdf exported.



Maybe it’s because I didn’t use system.file when using read.delim but I couldn’t get it to work. I am not familiar with system.files but thought that "files/structureindlabels.txt" should be substituted with the path to my label files but

inds <- read.delim(system.file("Z:/My Documents/LAB/LAB BOOK/Bluebells/SNP ARRAY/Analyses/pophelper/mylabels.txt", package="pophelper"),header=FALSE,stringsAsFactors=FALSE) produced this error

Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

Thank you

Markus

**Comment by royfrancis** [comment]
The `system.file()` is not needed if reading a file locally.

The below should work.

```r
 sfiles <- choose.files()
 slist <- readQ(files=sfiles)
 inds <- read.delim("mylabels.txt", header=FALSE, stringsAsFactors=FALSE)
 rownames(slist[[1]]) <- inds$V1
 plotQMultiline(slist, lpp=7, spl=70, useindlab=T, imgtype="pdf")
```
If not, then we need to inspect if `inds$V1` actually has a vector of the correct labels. And ensure that the first qlist element is renamed correctly like this `rownames(slist[[1]])`. If this still doesn't work, then you can send me the files and I can have a look.

**Comment by markusruhsam** [comment]
Hi Roy,

inds$V1 has a vector of the correct labels and rownames(slist[[1]]) has been renamed correctly but still no individual names in the plot. I attached the files – maybe you can have a look.

Thank you

Markus

**Comment by royfrancis** [comment]
I can't seem to find any attachments.

**Comment by markusruhsam** [comment]
As the files were attached to the last email but obviously didn’t come through I re-sent the files to your email address given in the pophelper paper.

**Comment by royfrancis** [comment]
Sorry for the delay, but your files do seem to work for me. I tried one file. I used the code below. See attached figure.

```
library(pophelper)

#read structure file
slist <- readQ(files="20000_run_6_f")

# plot using numeric numbering
plotQMultiline(slist,useindlab=F)

#read new labels
inds <- read.delim("mylabels.txt",header=FALSE,stringsAsFactors=FALSE)

# add labels as rownames to qlist
rownames(slist[[1]]) <- inds$V1

# plot with new labels.
plotQMultiline(slist,useindlab=T)

```

![20000_run_6_f-multiline-1](https://cloud.githubusercontent.com/assets/5083500/22379296/02c777b0-e4b9-11e6-8691-a8c6ec6bcffc.png)

**Comment by markusruhsam** [comment]
I just worked out why it didn’t work as I used

slist <- readQ(files=sfiles)
inds <- read.delim("mylabels.txt",header=FALSE,stringsAsFactors=FALSE)
rownames(slist[[1]]) <- inds$V1
plotQMultiline(slist[c(6)], lpp=7, spl=70, useindlab=T, imgtype="pdf")

when I should have replaced the 1 in rownames(slist[[1]]) with 6 as I instructed the program to plot the 6th run in plotQMultiline()

slist <- readQ(files=sfiles)
inds <- read.delim("mylabels.txt",header=FALSE,stringsAsFactors=FALSE)
rownames(slist[[6]]) <- inds$V1
plotQMultiline(slist[c(6)], lpp=7, spl=70, useindlab=T, imgtype="pdf")

Thanks for your help

Markus
