### ISSUE TITLE
plot structure individual labels on CLUMPP plot?

### ISSUE THREAD

**Issue by tommydevitt** [royfrancis/pophelper#34]
Is it possible to print the individual labels read in from structure runs on a plot of CLUMPP results? Or is it necessary to just provide a custom label file when plotting CLUMPP output?

**Comment by royfrancis** [comment]
Hmm.. No. The ind labels are unfortunately lost when running clumpp. The solution would be to manually read in the the labels as a text file and add it to the qlist object in R. Here is an example:

```
library(pophelper)

# read structure files with labels into an R qlist
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)[c(5,11,15)]
slist <- readQ(files=sfiles,indlabfromfile=T)

# read clumpp output file (say aligned) into an R qlist
cafile <- system.file("files/STRUCTUREpop_K4-combined-aligned.txt",package="pophelper")
calist <- readQ(files=cafile)

# add ind labels from structure qlist to the clumpp qlist
# for one run in the clumpp qlist
rownames(calist[[1]]) <- rownames(slist[[1]])

# you can change ind lab for all runs in the clumpp qlist
fun1 <- function(dfr) {rownames(dfr) <- rownames(slist[[1]]); dfr}
calist1 <- lapply(calist,fun1)
```

I think the order of individuals do not change after clumpp realignment. If that's true, then this is a solution.

**Comment by tommydevitt** [comment]
I think you're right, I don't think the order of individuals changes after
clumpp realignment. Thanks for the code. Great program, BTW!

Thanks,
Tom
