### ISSUE TITLE
Suppressing group label panel in plotQ?

### ISSUE THREAD

**Issue by KarlFetter** [royfrancis/pophelper#35]
Hi Roy,

Is there a way to suppress the group label panel in plotQ? I can't find a method for suppressing it? Something like showgrplab=F was what I am looking for. It appears that function works in plotQMultiline() but not plotQ().

Thanks!

**Comment by royfrancis** [comment]
Hi Karl,
That's a good point. The general idea was that if you are using the `grplab` argument, then you want the group labels to be shown. But, I guess there are situations where you want to use group labels, but don't want them shown on the plot. I can add `showgrplab` as an argument in the next update.

**Comment by royfrancis** [comment]
Argument 'showgrplab' added to `plotQ()` to hide group labels in v2.2.8.
