### ISSUE TITLE
Y-axis always display on the left, even sppos="left".

### ISSUE THREAD

**Issue by xiekunwhy** [royfrancis/pophelper#36]
Hi,
I found that yaxis always display on the left of panels, even sppos="left", can you add some options to move it to the right side of the panel?

Kun Xie.

**Comment by xiekunwhy** [comment]
For myself, I modified the source code in pophelper.R, 1) delete 2794 line, and add some judgement statement after 2834 line.
        gg_plot_panel <- gg_plot_panel+theme(plot.margin=grid::unit(c(0.2,0.05,indlabheight,0.1),"cm"))
        if(sppos=="left"){
        	gg_plot_panel <- gg_plot_panel+scale_y_continuous(position = "right", expand=c(0,0))
        } else {
          gg_plot_panel <- gg_plot_panel+scale_y_continuous(expand=c(0,0))
        }

**Comment by royfrancis** [comment]
The argument `sppos` is only to adjust the position of the strip panels and not the y-axis.
