### ISSUE TITLE
problem installing pophelper

### ISSUE THREAD

**Issue by eugeniadamato** [royfrancis/pophelper#37]
I am using R 3.5.1. in windows and I get the following message when trying to install from github:

_Downloading GitHub repo royfrancis/pophelper@master
from URL https://api.github.com/repos/royfrancis/pophelper/zipball/master
Installation failed: zip file 'C:\Users\Admin\AppData\Local\Temp\Rtmp8i7lPl\file1b70613d3162.zip' cannot be opened
Warning message:
In utils::unzip(src, exdir = target) : error 1 in extracting from zip file_

Then I downloaded the zipped file and trying to "install from locl file" option in R and still doesn't work. Nothing happens at all.

I tried an older version of R and the problem persist.

if anyone faced the same problem i would greatly appreciate sharing tips and advice
best
eu

**Comment by royfrancis** [comment]
Hi. Sorry I missed your message. This is the first time I hear about such as issue. It is probably a local issue with your system/environment. Did you manage to get this sorted out?
