### ISSUE TITLE
readQ to import 90% probability intervals

### ISSUE THREAD

**Issue by erynmcfarlane** [royfrancis/pophelper#38]
Hi,

This is a wonderful package that has solved a bunch of headaches for me recently, so thank you.

Is it possible to use readQ to read in probability intervals from a structure output? I can see them in the structure output textfile, but they're not imported in as part of the list.

Thanks so much!

**Comment by royfrancis** [comment]
Confidence intervals are read in v2.2.8.

**Comment by Astahlke** [comment]
This is a great feature! Can it be further developed to allow plotting confidence intervals on the structure plot?

**Comment by royfrancis** [comment]
Hmm.. Do you have any ideas on how this should look like? Examples? Thoughts?
