### ISSUE TITLE
Sort by group AND individual labels?

### ISSUE THREAD

**Issue by HeatherKates** [royfrancis/pophelper#4]
Hello! 
I want to generate a barplot where individuals are sorted by their population group and also have their labels displayed. 

I can sort individuals by group labels using plotQ:

`plotQ(qlist=qlist2[i],sortind="all",grplab=list("lab1"=grp$V2),sp=F,subsetgrp=c("Wild","Landrace","Improved"))`

OR

I can use individual labels using plotQMultiline:

```
inds <- read.delim("structureindlabels.txt",header=FALSE,stringsAsFactors=FALSE)
# add labels as rownames to qlist
rownames(qlist2[[1]]) <- inds$V1
#plot with individual labels
plotQMultiline(qlist2[i],spl=48,lpp=2,useindlab=T,sortind = "Cluster1")

```
However I can't find any way to both sort by group and label individuals in the same plot. It seems that this would be a very common need for users, so I must be missing something. Without this, it's extremely difficult for me to get or display the basic information about my data in one plot.

Thank you!
Heather Rose``

**Comment by royfrancis** [comment]
You need to use `plotQMultiline()` to view individual labels. `plotQMultiline()` does not really handle groups. But if you want to sort the individuals by group labels first and then by ind labels within group, it can be achieved by concatenating group and ind labels. Here is an example below:

```
library(pophelper)

#path to structure file
sfiles <- list.files(path=system.file("files/structure",package="pophelper"),full.names=T)
#read file
sf <- readQ(files=sfiles[1])

#path to individual labels
inds <- read.delim(system.file("files/structureindlabels.txt",package="pophelper"),header=F,stringsAsFactors=FALSE)
#read group labels
grp <- read.delim(system.file("files/structuregrplabels.txt", package="pophelper"), header=F,stringsAsFactors=F)

#join group labels and ind labels
newlabs <- paste0(grp$V1,"-",inds$V1)

#add new labs to data
rownames(sf[[1]]) <- newlabs

#plot multiline plot original order
plotQMultiline(sf,useindlab=T,barwidth=1)
```
![structure_01-multiline-1](https://cloud.githubusercontent.com/assets/5083500/24745023/65c1464e-1ab4-11e7-984a-169b865a18ec.png)
```
#order dataframe by row names and create a new qlist
new <- list(sf[[1]][order(rownames(sf[[1]])),])
#name the qlist (use as export filename)
names(new) <- "newsort"

#plot multiline plot sorted by labels
plotQMultiline(new,useindlab=T,barwidth=1)
```
![newsort-multiline-1](https://cloud.githubusercontent.com/assets/5083500/24745033/6b6ee894-1ab4-11e7-9ac3-e8bfaac887e4.png)

**Comment by HeatherKates** [comment]
Thanks so much- that makes sense. It would be great to have an option to sort individuals by clusters within groups, but I will use the information from the plotQMultiline() plot and display the plotQ() plot as a figure for publication/presentation. Thanks again.

**Comment by royfrancis** [comment]
I have put that on the to-do list :-)

**Comment by royfrancis** [comment]
Sorting individuals with group labels in `plotQMultiline()` implemented from `v.2.1.0`.
