### ISSUE TITLE
Unable to return plot while using grplab=label

### ISSUE THREAD

**Issue by CarBarJon** [royfrancis/pophelper#40]
Hello! 
I was hoping you could help me.  I used your program a couple of moths ago and everything was fine, but Now I'm experience a new problem that I didn't have before.
When I run Qplot()it runs perfect until i add the group label , in this moment the program does not return the plot. I change the return plot to TRUE , but, noting. For the moment I been able to save the images using exportplot=TRUE, but the pgn images its to small, and when I make it bigger I lose a lot of resolution. 
Its is what I get when I use grouplabel 
![Captura de pantalla 2019-03-09 a la(s) 21 16 09](https://user-images.githubusercontent.com/17257470/54080210-969c1700-42b0-11e9-83b4-418a254b6b25.png)

Using the same data, but removing the group label I have no problem... 
I wish you could help me. 
Thanks!

**Comment by royfrancis** [comment]
Can you send me a sample input file and the script that you use?

**Comment by slcapel** [comment]
Was this ever resolved?  I'm having the same issue, it generates the png but never returns the plot in R.  Here's my code:

```
> sfiles <- list.files(path = "~/Desktop/Work/STRUCTURE Output/")
> slist <- readQStructure(files = sfiles)
> locations <- read.delim("~/Desktop/Work/locations.csv", header = F, stringsAsFactors = F)
> plotQ(slist[4], clustercol = standard_12, showindlab = F, returnplot = T, exportplot = T, basesize = 5, quiet =T, ordergrp = T, grplab = locations)
```
And here's the output:

```
$plot
$plot[[1]]
TableGrob (4 x 1) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-3,1-1) arrange gtable[layout]
2 2 (4-4,1-1) arrange gtable[layout]

$data
$data$qlist
[1] NA

$data$grplab
[1] NA
```

**Comment by royfrancis** [comment]
Did you save the output to a variable and plot it? Here is a working example.

```
library(pophelper)
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
slist <- readQ(files=sfiles)
threelabset <- read.delim(system.file("files/metadata.txt", package="pophelper"), header=T,stringsAsFactors=F)

tmp <- plotQ(slist[1],grplab=threelabset[,1,drop=F],returnplot=T,exportplot=F)

plot(tmp$plot[[1]])
```

**Comment by slcapel** [comment]
That worked! I was just confused because it was returning the plot in R fine the way I was previously doing it before I specified the grplab option.  Thanks for the help and quick reply!!
