### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by rspfau** [royfrancis/pophelper#41]
I had it installed and working last month...but tried to use it today and it won't install. Tried on two separate computers.
-Russell

Installing package into ‘C:/Users/pfau/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'pophelper' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'ggplot2' was built under R version 3.5.3
ERROR: lazy loading failed for package 'pophelper'
* removing 'C:/Users/pfau/Documents/R/win-library/3.5/pophelper'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/pfau/AppData/Local/Temp/RtmpeiyZF8/file286c34155f0c/pophelper_2.2.8.1.tar.gz’ had non-zero exit status

**Comment by royfrancis** [comment]
I see you are on windows. What version of R are you using? The new version of pophelper has a minimum R requirement of R 3.5.0.

**Comment by rspfau** [comment]
vs. 3.5.2. Here's the full console:


R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "5.2"

$year
[1] "2018"

$month
[1] "12"

$day
[1] "20"

$`svn rev`
[1] "75870"

$language
[1] "R"

$version.string
[1] "R version 3.5.2 (2018-12-20)"

$nickname
[1] "Eggshell Igloo"

> # install dependencies and devtools
> install.packages(c("ggplot2","gridExtra","gtable","tidyr","devtools"),dependencies=T)
Installing packages into ‘C:/Users/pfau/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning: dependency ‘BiocInstaller’ is not available
trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/ggplot2_3.1.0.zip'
Content type 'application/zip' length 3621895 bytes (3.5 MB)
downloaded 3.5 MB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/gridExtra_2.3.zip'
Content type 'application/zip' length 1108422 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/gtable_0.2.0.zip'
Content type 'application/zip' length 85828 bytes (83 KB)
downloaded 83 KB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/tidyr_0.8.3.zip'
Content type 'application/zip' length 953832 bytes (931 KB)
downloaded 931 KB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/devtools_2.0.1.zip'
Content type 'application/zip' length 384745 bytes (375 KB)
downloaded 375 KB

package ‘ggplot2’ successfully unpacked and MD5 sums checked
package ‘gridExtra’ successfully unpacked and MD5 sums checked
package ‘gtable’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\pfau\AppData\Local\Temp\Rtmpg5a6Ie\downloaded_packages
> devtools::install_github('royfrancis/pophelper')
Downloading GitHub repo royfrancis/pophelper@master
colorspace (1.4-0 -> 1.4-1) [CRAN]
Installing 1 packages: colorspace
Installing package into ‘C:/Users/pfau/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
           binary source needs_compilation
colorspace  1.4-0  1.4-1              TRUE

  Binaries will be installed
trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.5/colorspace_1.4-0.zip'
Content type 'application/zip' length 2545223 bytes (2.4 MB)
downloaded 2.4 MB

package ‘colorspace’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\pfau\AppData\Local\Temp\Rtmpg5a6Ie\downloaded_packages
  
  
  
   checking for file 'C:\Users\pfau\AppData\Local\Temp\Rtmpg5a6Ie\remotesca412ab6ba5\royfrancis-pophelper-89e1ece/DESCRIPTION' ...
  
   checking for file 'C:\Users\pfau\AppData\Local\Temp\Rtmpg5a6Ie\remotesca412ab6ba5\royfrancis-pophelper-89e1ece/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\pfau\AppData\Local\Temp\Rtmpg5a6Ie\remotesca412ab6ba5\royfrancis-pophelper-89e1ece/DESCRIPTION'

  
  
  
-  preparing 'pophelper':
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information

  
  
  
-  checking for LF line-endings in source and make files and shell scripts

  
  
  
-  checking for empty or unneeded directories

  
  
  
-  building 'pophelper_2.2.8.1.tar.gz'

  
   

Installing package into ‘C:/Users/pfau/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'pophelper' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'ggplot2' was built under R version 3.5.3
ERROR: lazy loading failed for package 'pophelper'
* removing 'C:/Users/pfau/Documents/R/win-library/3.5/pophelper'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/pfau/AppData/Local/Temp/Rtmpg5a6Ie/fileca43f821ba9/pophelper_2.2.8.1.tar.gz’ had non-zero exit status
> library(pophelper)
Error in library(pophelper) : there is no package called ‘pophelper’

**Comment by rspfau** [comment]
I uninstalled R and reinstalled it. Seems to have solved the problem:
> # load library for use
> library(pophelper)
Loading required package: ggplot2
pophelper v2.2.8.1 ready.

**Comment by royfrancis** [comment]
It's strange. Anyway, I am glad you have resolved it.

**Comment by unribes** [comment]
I had the same problem with R 4.0.0 because my version of ggplot2 was built under the R version 4.0.2.
I updated R using the installr package on Windows and I was able to install pophelper afterwards.
