### ISSUE TITLE
Order of K out of control when I plot my data with population informations

### ISSUE THREAD

**Issue by xiekunwhy** [royfrancis/pophelper#42]
Hi,

When I plotting structure/admixtrue results with population informations, K = 2 ALWAYS follow by K=11, even though Q file names have been sorted in input list, can you tell me what was wrong there?

Here is my r script to plot my results.

fclum <- list.files(path = "pop-both", full.names = T, pattern = "merge")
qclum <- readQ(fclum)
sample_order <- read.table("demon2_pop_code.txt", header = T, stringsAsFactors = F)
ind_name <- sample_order[,1]
for(i in 1:length(qclum)){
  row.names(qclum[[i]]) <- ind_name
}
### determine orders and labels
mink <- 2
maxk <- 12
k_order <- vector()
if(maxk < 10){
  k_order <- 1:length(qclum)
} else if (maxk < 20) {
  end1 <- maxk - 10 + 1
  start2 <- end1 + 1
  k_order <- c(start2:length(qclum), 1:end1)
}
klab <- vector()
if(mink == 1){
  klab <- 2:maxk
} else {
  klab <- mink:maxk
}

prefix <- "demo_label"
plotQ(qclum[k_order], imgoutput="join",showindlab=T, showlegend=F, sortind = "all",
      indlabsize=0.5,indlabheight=0,indlabspacer=0.05,barbordersize=NA,
      outputfilename=prefix,imgtype="pdf", sharedindlab = F,
      useindlab = T, showyaxis = T, basesize = 10, sppos = "right", showticks = T,
      splab = paste0("K = ", klab), splabsize = 6, splabface = "bold",
      width = width, height = height, panelspacer = 0.02, dpi = 600, barbordercolour = NA,
      grplab=sample_order[,2,drop=FALSE], grplabsize=2, grplabheight = 4)

and got
![snp_pop](https://user-images.githubusercontent.com/17738229/55395416-16e22f00-5574-11e9-9e7d-09fff884b53b.png)

Best wishes,
Kun

**Comment by royfrancis** [comment]
Hi Kun,  Looks like the sorting order is string rather than numeric.  Perhaps it could be a bug related to sorting. Would you be able to send me some sample files (k=2 to few k > 10) to test?

**Comment by xiekunwhy** [comment]
Hi, here is a test data set generate from LEA package, K=2 to K=15.
[for_pophelper.zip](https://github.com/royfrancis/pophelper/files/3034372/for_pophelper.zip)

**Comment by royfrancis** [comment]
Hi Kun, I am able to replicate this issue. It seems like simply adding group labels changes the order of runs in a joined plot. I will look into this and update here when this is fixed. Thanks for reporting this.

**Comment by royfrancis** [comment]
Bug fixed in v2.2.9.
