### ISSUE TITLE
unable to read files

### ISSUE THREAD

**Issue by angelesdecara** [royfrancis/pophelper#43]
Hi!
I'm trying to read the admixture files I have on my mac, either from the very same directory or from directory .., but when I type
> afiles<- list.files(path=system.file(".",package="pophelper"), full.names=T)
>alist <- readQ(files=afiles)
I obtain
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 15 elements

Alternatively, if I do it from the directory above:
>  afiles<- list.files(path=system.file("Admix/",package="pophelper"), full.names=T)
> alist <- readQ(files=afiles)
I obtain this error
Error in readQ(files = afiles) : readQ: No input files.

All help will be greatly appreciated!

**Comment by royfrancis** [comment]
You need to modify this
`afiles <- list.files(path=system.file(".",package="pophelper"), full.names=T)`
to
`afiles <- list.files(path=".", full.names=T)`

The `system.file()` is used to read files from the R package.

**Comment by royfrancis** [comment]
A clumpp file usually contains multiple tables. And they should all be the same number of rows. ie; same number of samples/individuals. The error says that is not the case with your file. If you can send me one of your clumpp files, I can take a look.

**Comment by angelesdecara** [comment]
Sorted! In that folder, I have also log files and a fam file, besides the .P and .Q files generated by admixture, so by moving the P and Q files to another folder, I can do the plots there. Or so far...

> plotQ(alist[1])
Drawing plot ...
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found

Many thanks for your help and sorry to bother you... I am attaching you my Q file for K=10, just in case.
[cosa.txt](https://github.com/royfrancis/pophelper/files/3211132/cosa.txt)

**Comment by royfrancis** [comment]
Your file works as expected.

```
x <- readQ("/path/cosa.txt")
plotQ(x)
```
