### ISSUE TITLE
Workflow error at generating qlist

### ISSUE THREAD

**Issue by GrimPerez** [royfrancis/pophelper#45]
Good day,

I want to thank you for your patience and time. I am new to using pophelper. I read the "Pophelper 2.2.9 Roy M Francis | 14-Apr-2019" before attempting to use pophelper. I have acquired my STRUCTURE results for K1-K10 with 10 repeats each (100 total outputs). I am using RStudio in MAC.

I am encountering an error at clumppExport(qlist) as seen below.

+ clumppExport(qlist)
+ setwd("~/Desktop/structurepop")
Error: unexpected '/' in:
"clumppExport(qlist)
setwd("~/"
> collectClumppOutput(prefix="pop", filetype="aligned") 
Directories processed: 0
Files copied: 0
[1] 0 0
> collectClumppOutput(filetype="both")
Directories processed: 0
Files copied: 0
[1] 0 0
> 

This is the set of commands that I am trying to use to plot Q and to acquire plots produced by the Evanno method.

library(pophelper)
setwd("~/Desktop/structurepop")
sfiles <- list.files(path="~/Desktop/structurepop, full.names=T)
readQ(files=sfiles)
tabulateQ(qlist) 
summariseQ(df1)
evannoMethodStructure(df2, exportplot=T)
clumppExport(qlist)
setwd("~/Desktop/structurepop")
collectClumppOutput(prefix="pop", filetype="aligned") 
collectClumppOutput(filetype="both")
plotQ(qlist)
plotQ(qlist,imgoutput="join")
plotQMultiline(qlist[1])
plotQMultiline(qlist[1], spl=70, lpp=10)

analyseQ(qfiles)

Your input is sincerely appreciated. Thanks.

**Comment by royfrancis** [comment]
Hi, What error do you get? Also, if possible, could you please send me some sample files? Thanks.

**Comment by GrimPerez** [comment]
Good morning Roy Francis,

I apologize for my late reply. I was away from any form of technology this whole time.

Please find attached 3 files as follows:
1_pop_K7-combined-merged
2_MK7Sorted
3_sample plot

I was able to make the scripts work. I was hoping you could help me out with the following.


  1.  How can I generate a plot as seen in "3_sample plot?"
  2.  I was unable to change the labels of the plot. I tried changing the numeric labels to word labels in the 1_pop_K7-combined-merged, but my plots still generated numeric labels.

Your help is sincerely appreciated. Thank you so much and I appreciate any time you can spare me.


Sincerely,
Grimar A. Perez



________________________________

**Comment by GrimPerez** [comment]
[1_pop_K7-combined-merged.txt](https://github.com/royfrancis/pophelper/files/3337298/1_pop_K7-combined-merged.txt)
![2_MK7Sorted](https://user-images.githubusercontent.com/51880237/60312406-683c6780-9985-11e9-8cd4-400a62948215.png)
<img width="1012" alt="3_sample plot" src="https://user-images.githubusercontent.com/51880237/60312407-683c6780-9985-11e9-9f46-982f3c842e51.png">

The files. Sorry.

**Comment by royfrancis** [comment]
Hi,
I think the plot you have looks similar to the attached figure. They are both sorted by the largest proportions. The data is just different, that's all. To change individual labels, you need to manually read in the labels to R and add that as the rownames of the qlist object.

```
library(pophelper)
# read clumpp file as a qlist
x <- readQClumpp("../runs/structureruns/grimperez/1_pop_K7-combined-merged.txt")
# read labels as a tab delimited text file (labels in same order as in clumpp file)
labs <- read.csv("../runs/structureruns/grimperez/labels.csv",header=F,stringsAsFactors=F)
# add labels to qlist
rownames(x$`1_pop_K7-combined-merged-1`) <- labs$V1
```

Then, use `showindlab=T` and `useindlab=T` during plotting.

```
plotQ(x,exportplot=F,returnplot=T,showindlab=T,useindlab=T)
```

**Comment by GrimPerez** [comment]
Thank you very much. Your input was very helpful. 

If I may ask, is it possible to calculate %admixture within the pophelper workflow? For example: K= 3, % admixture for for each cluster?

**Comment by royfrancis** [comment]
Hmmm. I am not quite sure what you mean. The admixture values are in proportions already which is the same as percentage. For each individual, the values sum to 1. 

For example; K=2
```
Sample  Cluster1 Cluster2
Sample1 0.7      0.3
```

or K=3
```
Sample  Cluster1 Cluster2 Cluster3
Sample1 0.7      0.2      0.1
```

**Comment by GrimPerez** [comment]
Thank you for your kind response. I will try to elaborate a bit more on what I mean. 
For example: if I have K=3, I would like to know the percentage of genotypes (%) containing a degree of intermixing greater than 10% for each cluster. 
K=3, n=120, Cluster1= 40, Cluster2=40, Cluster3=40. Cluster1, 20 of 40 genotypes (50%) contain a degree of intermixing greater than 10%.

Is this possible to calculate using the data generated through pophelper? Thank you again for your time and patience.


Sincerely,
Grimar A. Perez
