### ISSUE TITLE
Sorting when ordered by group

### ISSUE THREAD

**Issue by kbcn** [royfrancis/pophelper#49]
Hello!  I love this package, and I'm wondering if you can help me with this. I made a plot where I have sorted by group and also want to sort by clusters. I tried setting "sortind=all", but I guess what I am looking for is to first sort by cluster 1, then cluster 2, etc. "sortind=all" seems to do this for my first population, but then the others aren't fully sorted.

I am running pophelper 2.3.0 on R version 3.5.2

Here is the code I am using:

pk3 = plotQ(qlist=qlist[3],
           returnplot=T, exportplot=F, quiet=T, basesize=12,
           grplab = poplabel, grplabsize=4, linesize=0.8, pointsize=4,
           ordergrp = T, showyaxis=T, showlegend = T,
           clustercol = clist$merry_5,
           subsetgrp=c("A", "B", "C", "D", "E", "F"),
           sortind = "all")

Thanks!

**Comment by royfrancis** [comment]
Hi, I see you have the script above. Could you also add the input files (`qlist[3]`,`grplab`) that you use and the output plot that you get? Thanks.
