### ISSUE TITLE
Cant download pophelper version 2.3.0 to get alignK function

### ISSUE THREAD

**Issue by BKT0** [royfrancis/pophelper#50]
Currently using R v3.5.3 using pophelper.  Need alignK function, which is not offered in version pophelper 2.2.9.  Do not know how to get updated version of pophelper.  Have tried using R version 3.5.0 but still shows as version 2.2.9 of pophelper.  Have tried to download from both CRAN and GitHub.  Please help.  Really need the alignK and mergeQ function.

**Comment by royfrancis** [comment]
Hi, I have just tried it out on R 3.5.3 and it seems to work fine. Can you describe the code you ran and the error?

**Comment by BKT0** [comment]
Hi the code we ran was:
k2list<-readQ(choose.files(multi = TRUE))
print(k2list)
k2align<-alignK(k2list)

error we received is "Could not find function “alignK”." 

We have pophelper version 2.2.9 which seems to be the one available on CRAN (and github)
The option for alignK does not show up within the package details

**Comment by royfrancis** [comment]
You have to install the newer version for these functions. Run the steps below

```r
install.packages(c("ggplot2","gridExtra","gtable","label.switching","tidyr","devtools"),dependencies=T)
devtools::install_github('royfrancis/pophelper')
library(pophelper)
```

And if you have issues with this, let me know.

**Comment by BKT0** [comment]
Thank you for much for your quick responses.
We have gotten this to work on our computer now!
We really appreciate your help.
