### ISSUE TITLE
I am unable to reach Webapp of pophelper. Page is not loading. Kindly let me know hoe can I solve this issue.

### ISSUE THREAD

**Issue by azharjoiya** [royfrancis/pophelper#51]
* Please describe the circumstances under which you got the error
* Paste the code that you executed
* Paste the error message returned
* What version of pophelper are you running?
`packageVersion("pophelper")`
* What version of R are you running?
`R.version.string]`
* What OS are you running?
`Sys.info()["sysname"]`
* Depending on the error, I might ask for the input files to reproduce the error.

**Comment by azharjoiya** [comment]
I am not well familiar with R, therefore I am using Pophelper Webapp. I am unable to open it. The page is not loading and giving an error. Please help me in this regard. Your efforts will be highly appreciated

**Comment by royfrancis** [comment]
I wouldn't recommend the webapp. I would suggest that you use the pophelperShiny R package which provides a graphical user interface. Instructions are provided here: http://royfrancis.github.io/pophelperShiny/

In short, Install R on your computer, then run a few commands and it should open up the interactive web app in your browser. If you have difficulty getting this to work, feel free to comment below.
