### ISSUE TITLE
No picture output

### ISSUE THREAD

**Issue by xujinshengjsxu** [royfrancis/pophelper#52]
Hi,
I am new to using pophelper. I'm wondering if you can help me with this problem. I made a plot follow the tutorial. But it only generates outputs as follows, no pictures. After remove the argument grplab, it runs correctly and i can get the picture.   

![image](https://user-images.githubusercontent.com/41499027/69472705-72ee1200-0de8-11ea-8fdb-c10a6a36f6a5.png)

Thanks.

**Comment by royfrancis** [comment]
Not sure where you are running it. If you are running that in RStudio, the RStudio plot panel should show a plot. If you running that in a command line you won't see anything. By setting `exportplot=F`, the plot is not exported. If you set `exportplot=T`, it will export a plot. And this `returnplot=T` means the plot is returned. You could save it to a variable. And then use that to print.

```
x <- plotQ(slist[c(1,3)],imgoutput="join",returnplot=T)
ggsave("image.png",x$plot[[1]])
```

**Comment by xujinshengjsxu** [comment]
sorry, I have solved it. Thanks for your reply!

**Comment by salihtuna** [comment]
I am having the exact same issue. I am using Rstudio and when I set the grplab, the picture is not printed on the screen,  it only gets exported even though I specify the returnplot=T.

**Comment by royfrancis** [comment]
@salihtuna Try this little example and see if it works.

```
slist <- readQ(list.files(path=system.file("files/structure",package="pophelper"), full.names=T))

# this may be automatically plotted to screen
plotQ(slist[1],returnplot=T,exportplot=F,quiet=T,basesize=11)

# now with group labels
threelabset <- read.delim(system.file("files/metadata.txt", package="pophelper"), header=T,stringsAsFactors=F)

# this is not automatically plotted on screen
plotQ(slist[1],returnplot=T,exportplot=F,quiet=T,basesize=11,
            grplab=threelabset,grplabsize=4,linesize=0.8,pointsize=4)

# so save it and use plot
p1 <- plotQ(slist[1],returnplot=T,exportplot=F,quiet=T,basesize=11,
            grplab=threelabset,grplabsize=4,linesize=0.8,pointsize=4)
plot(p1$plot[[1]])
```

**Comment by salihtuna** [comment]
@royfrancis Thanks. it works fine now.
