### ISSUE TITLE
Different lengths of SD bars

### ISSUE THREAD

**Issue by YI-stone01** [royfrancis/pophelper#54]
I'm a new user of your pophelper. I have a question. Why do SD bars (i.e. above mean and below mean) have different lengths in Fig. A of Evanno plots?

**Comment by royfrancis** [comment]
I think it is supposed to be equal length. I can look into this when I get some time.

**Comment by YI-stone01** [comment]
For example, A of "Fig: Plots from Evanno method" in the homepage of your pophelper website (http://www.royfrancis.com/pophelper/index.html) has different lengths.

**Comment by royfrancis** [comment]
Ok. Found the issue. So, the error bars in the first plot are currently showing min and max. I will fix it to show sd in the next release. Thanks for pointing this out.

**Comment by YI-stone01** [comment]
Thank you for your response.
