### ISSUE TITLE
The colors of clusters across K are inconsistent.

### ISSUE THREAD

**Issue by cyril698** [royfrancis/pophelper#56]
Hi,
I'm a new user of your pophelper. Now I have a problem. When plotting k=3,4,5,6, the colors of the upper and lower corresponding clusters are inconsistent. 
I would like to keep the same color for those clusters that are the same across Ks.
I used alignK(alist[c(1:4)]), but it didn't seem to work.
How can I solve it? 
Thanks!

**Comment by royfrancis** [comment]
Hi, Can you post an example plot with and without align? And also please post the code that you used.

**Comment by cyril698** [comment]
Here is my code:
require(pophelper)
afiles<-list.files(path="/Users/tt",full.names=T)
alist<-readQ(files=afiles)
tr1 <- tabulateQ(alist, writetable=TRUE)
summariseQ(tr1, writetable = TRUE)
fn1 <- function(x) attr(x,"k")
spnames <- paste0("K=",sapply(alist,fn1))

bfiles<- "/Users/label.txt"
labset <- read.delim(bfiles,header=T,stringsAsFactors=F)
head(labset)
nrow(labset)
sapply(labset, is.character)
data.frame(labset)

plotQ(alignK(alist[c(1:3)]),imgtype="pdf",imgoutput="join",splab=spnames,splabsize=2,basesize=1,showyaxis=T,panelspacer=0.3,grplab=labset,ordergrp=T,grplabangle=90,grplabjust=0.1,grplabheight=0.1,grplabpos=0.5,grplabsize=0.3,linesize=0.1,linepos=1,pointsize=0.1,showdiv=FALSE,sharedindlab=F,grpmean=T,subsetgrp=c(......))

and my example plot:
<img width="679" alt="截屏2020-02-02下午3 08 56的副本" src="https://user-images.githubusercontent.com/60483748/73604628-ac07e700-45ce-11ea-83e1-9f0f6b79216d.png">

**Comment by royfrancis** [comment]
In my example file, I think it works.

```
sfiles <- list.files(path=system.file("files/structure",package="pophelper"),full.names=TRUE)
slist <- readQ(sfiles)
plotQ(xlist[6:8],imgoutput="join",exportplot=F,returnplot=T,,showlegend=T)
```

![0](https://user-images.githubusercontent.com/5083500/74109437-d1bf5e00-4b83-11ea-81ca-101db88bd321.png)

`plotQ(alignK(xlist[6:8]),imgoutput="join",exportplot=F,returnplot=T,showlegend=T)`

![1](https://user-images.githubusercontent.com/5083500/74109441-d71ca880-4b83-11ea-88dd-d0958faa659e.png)

If you can send your three files, I can try to rerun it just to verify.

**Comment by cyril698** [comment]
Thank you for your reply.
I changed my dataset, and it worked.

**Comment by RvV1979** [comment]
Hi Roy, 
I am having trouble aligning K based on my slist (attached in RDS format here: (https://github.com/royfrancis/pophelper/files/12670714/slist.RDS.zip) )

my code
```
slist<-readRDS("slist.RDS")
plotQ(slist,returnplot = T, exportplot =F, imgoutput="join")
```
generated the plot below:
![plotq_slist](https://github.com/royfrancis/pophelper/assets/9930371/1b95eb01-0788-4ea8-ad8b-a6e780ad50b0)

my code 
`plotQ(alignK(slist),returnplot = T, exportplot =F, imgoutput="join")`
including cluster alignment generated the plot below:
![plotQ_alignK_slist](https://github.com/royfrancis/pophelper/assets/9930371/b25e409b-e512-45da-accd-852fb6dfc248)

As you can see, cluster alignment is solved within each k. However, it is nowhere near perfectly aligned across different k. Do you have some advice on how to improve this?

Thanks
