### ISSUE TITLE
Error: (converted from warning) Setting LC_CTYPE failed, using "C"

### ISSUE THREAD

**Issue by Annetteta** [royfrancis/pophelper#58]
Hi, I have problems installing pophelper in R; I use your code on a Mac-version of R 3.6.1 and get the following message: Warning message:
package 'pophelper' is not available (for R version 3.6.1) 
Any help would be appreciated  :) 

BEst, 
Annette

**Comment by royfrancis** [comment]
Hi Annette,
Is this the code you used?
`devtools::install_github('royfrancis/pophelper')`

Let me know the full code you use and all the error that you get.

**Comment by Annetteta** [comment]
Hi, thanks for your fast reply!
and yes, that was amongst the codes I tried, getting the following error:

Downloading GitHub repo royfrancis/pophelper@master
tar: Failed to set default locale
tar: Failed to set default locale
-  building 'pophelper_2.3.0.tar.gz'tion ...3/fs27h94x643c4mtwfqpqg14c0000gn/T/Rtmp5mH6F7/remotes6a9a57bf376e/royfrancis-pophelper-3ad0dba/DESCRIPTION' ...
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'pophelper' from GitHub:
  (converted from warning) installation of package '/var/folders/z3/fs27h94x643c4mtwfqpqg14c0000gn/T//Rtmp5mH6F7/file6a9a4ad043c3/pophelper_2.3.0.tar.gz' had non-zero exit status

**Comment by royfrancis** [comment]
This is a system specific issue on your machine. Open a clean R session and run this.

`system('defaults write org.R-project.R force.LANG en_US.UTF-8')`

Then restart R and try the installation again.

**Comment by evnovaes** [comment]
Hi royfrancis.

Thanks a lot for your last suggestions. I was facing the same problem as Annetteta on a MacOS (Catalina). After I followed your suggestion, the installation worked.

Thanks

**Comment by aramo685** [comment]
Hi royfrancis
I followed your instructions to install pophelper in R, but it failed. I am using windows and R version 4.0.2. It shows the following error message. Please help me in this regards. 


##
package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'pophelper' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
> # check version
> packageDescription("pophelper", fields="Version")
[1] NA
Warning message:
In packageDescription("pophelper", fields = "Version") :
  no package 'pophelper' was found

**Comment by royfrancis** [comment]
Can you please open this as a new issue? Thanks
