### ISSUE TITLE
Failed to install "pophelper"

### ISSUE THREAD

**Issue by dongyiyi** [royfrancis/pophelper#61]
I tried from GitHub link to install the package, but I got an error:
Error: Failed to install 'pophelper' from GitHub:
  (converted from warning) installation of package ‘C:/......../Local/Temp/Rtmpczfwm3/file4e9496f5b47/pophelper_2.3.0.tar.gz’ had non-zero exit status.
The run environment: In windows 10 and R 3.5.3

**Comment by liufy11** [comment]
try pophelper v2.2.9

**Comment by Vaniavr** [comment]
Hello royfrancis

I having issues in installing pophelper. Please see the error.

Error: Failed to install 'pophelper' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Joshi/AppData/Local/Temp/RtmpURnDjc/file1ab464784d0a/pophelper_2.3.0.tar.gz’ had non-zero exit status

**Comment by Vaniavr** [comment]
If this solves by installing through a zip file. Could you please let me know where can I find zip file. Thanks.
