### ISSUE TITLE
Sort individual labels

### ISSUE THREAD

**Issue by gubrins** [royfrancis/pophelper#64]
Good afternoon,

First of all, I want to say that I'm really happy using the pophelper package, is really well build.
I think my doubt is quite simple. I know I can sort my samples by group, but I would like to sort individual samples, as I want to plot my structure plot with a phylogenetic tree. I've been trying to find this option but I did not manage, is it possible to do it?

Regards,
Gabriel

**Comment by royfrancis** [comment]
Hey Gabriel,
If you have individual labels already in your object, then you can just sort by those labels. Otherwise, you need to add the labels first. Below is an example.

```
library(pophelper)

# read structure files with individual labels
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
slist <- readQ(files=sfiles,indlabfromfile=T)

# otherwise add your own individual labels
inds <- read.delim(system.file("files/structureindlabels.txt",package="pophelper"),header=FALSE,stringsAsFactors=F)
# if all runs are equal length, add indlab to all runs
if(length(unique(sapply(slist,nrow)))==1) slist <- lapply(slist,"rownames<-",inds$V1)
```

Plot with default order.

```
# plot
plotQ(slist[1],returnplot=T,exportplot=F,quiet=T,basesize=11,showindlab=T,useindlab=T)
```

![rp2](https://user-images.githubusercontent.com/5083500/92808193-d10dd500-f3bb-11ea-945d-3ec7717a83cf.png)

Sort by individual labels.

```
# sort by individual labels
plotQ(slist[1],returnplot=T,exportplot=F,quiet=T,basesize=11,showindlab=T,useindlab=T,sortind = "label")
```

![rp1](https://user-images.githubusercontent.com/5083500/92808237-dc610080-f3bb-11ea-978f-168943fd773e.png)

**Comment by gubrins** [comment]
Thank you very much for your answer. I knew about this, but it only sorts the label alfabetically/numerically. What about if I want to have individual I12578 (your second individual starting on the left) as the first individual appearing in the plot? Can I do that?

Regards,
Gabriel

**Comment by royfrancis** [comment]
Well.. if you need some custom order, then it has to be done manually. Here is an example.

```
library(pophelper)

# read structure files with individual labels
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
slist <- readQ(files=sfiles,indlabfromfile=T)
```

Let's take out one run and 5 individuals to simplify.

```
d1 <- slist[[1]][85:89,]
> d1
       Cluster1 Cluster2
I13892    0.505    0.495
I13893    0.866    0.134
I13894    0.966    0.034
I13895    0.706    0.294
I13896    0.840    0.160
```

Then give a custom sorting order. Let's say we swap positions 2 and 3.

```
d2 <- d1[c(1,3,2,4:5),]
> d2
       Cluster1 Cluster2
I13892    0.505    0.495
I13894    0.966    0.034
I13893    0.866    0.134
I13895    0.706    0.294
I13896    0.840    0.160
```

Convert to list and name them.

```
l1 <- list(d1)
names(l1) <- c("original")
l2 <- list(d2)
names(l2) <- c("reordered")
```

Plotting

```
# plot
plotQ(l1,returnplot=T,exportplot=F,quiet=T,basesize=11,showindlab=T,useindlab=T)
plotQ(l2,returnplot=T,exportplot=F,quiet=T,basesize=11,showindlab=T,useindlab=T)
```

![a1](https://user-images.githubusercontent.com/5083500/93132192-80f18400-f6d5-11ea-97fe-d132983959aa.png)
![a2](https://user-images.githubusercontent.com/5083500/93132202-84850b00-f6d5-11ea-806f-499357ad5715.png)

Individual 2 and 3 has been swapped around.

But, you need to do this across all your runs. If you have different order in different runs within a qlist, it might be a mess during plotting.

**Comment by royfrancis** [comment]
Here is an example across all runs in a qlist.

For simplicity, let's pick first 5 individuals from all runs

```
slist1 <- lapply(slist,function(x) x[1:5,])
slist1
$structure_01
Cluster1 Cluster2
I13825    0.965    0.035
I13826    0.977    0.023
I13827    0.961    0.039
I13828    0.975    0.025
I13829    0.974    0.026

$structure_02
Cluster1 Cluster2
I13825    0.965    0.035
I13826    0.977    0.023
I13827    0.962    0.038
I13828    0.975    0.025
I13829    0.974    0.026

$structure_03
Cluster1 Cluster2 Cluster3
I13825    0.911    0.067    0.023
I13826    0.891    0.089    0.019
I13827    0.044    0.931    0.025
I13828    0.919    0.058    0.023
I13829    0.099    0.879    0.022
...
```

Let's swap position 2 and 3 in all runs

```
slist2 <- lapply(slist1,function(x) x[c(1,3,2,4:5),])
slist2
$structure_01
       Cluster1 Cluster2
I13825    0.965    0.035
I13827    0.961    0.039
I13826    0.977    0.023
I13828    0.975    0.025
I13829    0.974    0.026

$structure_02
       Cluster1 Cluster2
I13825    0.965    0.035
I13827    0.962    0.038
I13826    0.977    0.023
I13828    0.975    0.025
I13829    0.974    0.026

$structure_03
       Cluster1 Cluster2 Cluster3
I13825    0.911    0.067    0.023
I13827    0.044    0.931    0.025
I13826    0.891    0.089    0.019
I13828    0.919    0.058    0.023
I13829    0.099    0.879    0.022
...
```

**Comment by gubrins** [comment]
Thank you very much!!
