### ISSUE TITLE
unable to remove strip panel

### ISSUE THREAD

**Issue by amiesett** [royfrancis/pophelper#66]
Hi, I'm really appreciating this package as I explore results from several methods for inferring ancestry coefficients! I think I've run into a bug though that is complicating creating some final figures. I can't seem to turn off the strip panel. After failing to figure it out for plots of my own data, I've given it one last attempt with some of the data you include with the package using
* Pophelper 2.3.0
* R version 3.5.1
* on Windows
Here's an example of some code I've tried:

`afiles<- list.files(path=system.file("files/admixture",package="pophelper"), full.names=T)`
`alist <- readQ(files=afiles)`
`testp <- plotQ(alist[1], showsp=F, exportplot=T, returnplot=T)`
`testp$plot[[1]]`

And the resulting plot:
![admixture_01](https://user-images.githubusercontent.com/16678168/95635677-af534c80-0a52-11eb-94bd-6b97f7c83f4a.png)

Thanks in advance for any insight!
Amie

**Comment by royfrancis** [comment]
Sorry for the late reply. Try this

```
testp$plot[[1]]+
 theme(
  strip.background = element_blank(),
  strip.text.y = element_blank())
```
