### ISSUE TITLE
Is there a way to put a "Q-value" lab in Y axis?

### ISSUE THREAD

**Issue by ronahuel** [royfrancis/pophelper#68]
I've tried many ways to do it
![FinalStruct](https://user-images.githubusercontent.com/50923627/100021691-a7602980-2dc0-11eb-939b-fbf6ef7722b3.png)

plot1 <- plotQ(qlist=alist[1],grplab = lab3, showyaxis = T,ticksize=1,splab=spnames[1],
               showsp = F, showlegend = F, showticks = T,exportplot=F,splabsize = 0,
               showdiv = T, showindlab = F,returnplot=T,grplabsize=3.5,indlabsize=10,
               titlesize = 3, showtitle = F,showsubtitle = F,clustercol=c("#2c7bb6","#d7191c"))+labs(y=c("Q-value"))

plot2 <- plotQ(qlist=alist[2],grplab = lab3, showyaxis = T,ticksize=1,splab=spnames[2],
               showsp = F, showlegend = F, showticks = T,exportplot=F,splabsize = 0,
               showdiv = T, showindlab = F,returnplot=T,grplabsize=3.5,indlabsize=10,
               titlesize = 3, showtitle = F,showsubtitle = F,clustercol=c("#2c7bb6","#d7191c","#fdae61"))

grid.arrange(plot1$plot[[1]],plot2$plot[[1]],ncol=1)

png("FinalStruct.png", width=16, height=5, units="in", res=300)
grid.arrange(plot1$plot[[1]],plot2$plot[[1]],ncol=1)
dev.off()

tryed for example, plot1$plot[[1]]+labs(y = "Q-value") but i got an error. Also i've tried change the splab but it goes to the right side of the Q-values instead of the left. 

Any help? 
BTW: thanks for your package, has been very useful !

**Comment by royfrancis** [comment]
Yes, `labs(y = "Q-value")` is correct. In addition, axis title needs to be to be enabled in the theme `theme(axis.title.y=element_text())`. I have also added `color="grey30"` so that the color matches the other elements. Below is an example.

```
library(pophelper)

# read data
sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)
slist <- readQ(files=sfiles,indlabfromfile=T)

# plot
plotQ(slist[1],returnplot=T,exportplot=F,showyaxis=T)$plot[[1]]+
  labs(y="Q value")+
  theme(axis.title.y=element_text(color="grey30"))
```
