### ISSUE TITLE
The space between individual labels and barplot are so big.

### ISSUE THREAD

**Issue by xiekunwhy** [royfrancis/pophelper#8]
Hi,
I like this tool very much. But I found that the individual labels are to far from the barplot when I showindlab, any options to close down these two?

Best.
Kun Xie.

**Comment by royfrancis** [comment]
Hi Kun, I will add some arguments to control that.

**Comment by xiekunwhy** [comment]
Thank you for your reply.

**Comment by royfrancis** [comment]
Argument `indlabspacer` added in version `2.2.1`.
