### ISSUE TITLE
How to modify Y-axis color & label

### ISSUE THREAD

**Issue by MinamiIwata** [royfrancis/pophelper#86]
Hi,
I am very excited to have found this very useful tool.
In the process of using this tool, I'd like to modify the label color and value of the Y axis in barplot.
I was wondering if such functions have already been implemented.
If so, I would like to know how to do it.

Sorry, my English is not very good.
Thank you for your support.

**Comment by royfrancis** [comment]
Did you manage to do this or do you still need help?

**Comment by MinamiIwata** [comment]
Thank you for your reply.
First of all, I apologize for adding unnecessary operations, as I was not familiar with Git Hub.
I have not been able to solve this problem yet.
If you have a solution, please let me know.
My best thanks for your help.

**Comment by royfrancis** [comment]
The plot can be modified using [ggplot2 theme](https://ggplot2.tidyverse.org/reference/theme.html). Here is an example:

```
library(pophelper)
library(ggplot2)

sfiles <- list.files(path=system.file("files/structure",package="pophelper"), full.names=T)[1]
slist <- readQ(files=sfiles)

# save output to variable
x <- plotQ(slist,exportplot=FALSE,returnplot=TRUE,basesize = 12,showyaxis=T,showindlab=T)

# extract plot
y <- x[[1]][[1]]
y
```
![a](https://user-images.githubusercontent.com/5083500/150430712-aa542074-0758-43c7-ab7f-bfeb4edc2773.png)

Then, we add a y axis label, change the x axis text to light blue, y axis text to red and finally y axis title to green.

```
# modify plot using ggplot
y <- y+labs(y="New axis title")+
      theme(axis.text.x=element_text(color="steelblue"),
            axis.text.y=element_text(color="red"),
            axis.title.y=element_text(color="green"))
y
```
![b](https://user-images.githubusercontent.com/5083500/150430843-06b51362-314a-477e-9451-529cad7053c3.png)

**Comment by MinamiIwata** [comment]
Thank you for your reply and for the sample code!
This code gave me exactly the output results I was seeking!
Sincerely.
