### ISSUE TITLE
Show all panel's individual labels when imgoutput = "join" && align labels to a special k's order

### ISSUE THREAD

**Issue by xiekunwhy** [royfrancis/pophelper#9]
Hi, Roy Francis, I still have some needs when using pophelper.
For plotQ(), 
1st , when sortind = "all" & imgoutput = "join", I need to show individual labels of each k panel separately instead of show them only once at bottom of the whole picture. I known I can set imgoutput = "sep" and showindlab = T and then paste each picture together using AI or some other programs, but it’s not convenient for me, so can you add some options to allow user to show all panel’s individual labels?
2nd , if showindlab=T, all other k panels were aligned according to first k panel’s order, but sometimes we need to aligned to another k panel(not the first panel), can you add some options to specified a special k to be aligned to?
Best,
Kun Xie.

[plotQ.pdf](https://github.com/royfrancis/pophelper/files/1150448/plotQ.pdf)

**Comment by royfrancis** [comment]
Hi Kun, Thank you for the suggestions. I will add these to the to-do list. To add, in a joined plot, you can change the order of the panels simply by changing the order of the runs in the qlist.

```
plotQ(qlist[1:2],imgoutput="join")
plotQ(qlist[c(2,1)],imgoutput="join")
```

**Comment by xiekunwhy** [comment]
OK, thank you very much.

**Comment by xiekunwhy** [comment]
Hi, me again, can now "show ind labs on all panels in joined plot" works ?
Best,
Kun Xie.

**Comment by royfrancis** [comment]
Argument `sharedindlab` added to control if individuals labels are shown once or below every plot when using `imgoutput="join"`. Added in version `2.2.4`. Note that `sharedindlab` cannot be used when sorting by 'all' or a cluster.
